name: Build Polyphone for MacOS

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      
env:
  QT_VERSION: '6.6.2'

jobs:
  build-macos:
    runs-on: macos-15
    
    steps:
      - name: Set VERSION from tag
        run: echo "VERSION=${{ inputs.tag }}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Update macOS plist version
        run: |
          CLEAN_VERSION=$(echo "$VERSION" | sed -E 's/^([0-9]+)\.([0-9]+)(\.([0-9]+))?.*/\1.\2.\4/')
          if [[ "$CLEAN_VERSION" =~ \.$ ]]; then
            CLEAN_VERSION="${CLEAN_VERSION}0"
          fi
          echo "Setting plist version to $CLEAN_VERSION"
          PLIST_FILE="packaging/mac/polyphone.plist"
          sed -i -E "s|(<key>CFBundleShortVersionString</key>[[:space:]]*<string>)[^<]+|\1$CLEAN_VERSION|" "$PLIST_FILE"

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: mac
          target: desktop
          arch: clang_64

      - name: Install dependencies
        run: |
          brew install \
            libsndfile \
            libogg \
            libvorbis \
            flac \
            lame \
            mpg123 \
            opus

      - name: Build
        run: |
          cd sources
          qmake polyphone.pro CONFIG+=release
          make -j$(sysctl -n hw.ncpu)

      - name: Create DMG
        run: |
          cd sources
          macdeployqt ../macos/polyphone.app -dmg
          mv ../macos/polyphone.dmg ../macos/Polyphone_${{ env.VERSION }}-macOS.dmg

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: polyphone-macos-installer
          path: macos/*.dmg
          retention-days: 7
          if-no-files-found: error
